### ISSUE TITLE
change the color of line number column

### ISSUE THREAD

**Issue by hzonuz** [gryf/wombat256grf#1]
Hi, I like your colorscheme and I think it's one of the most beautiful themes I've ever seen in Vim.
But the color of line number column in the left is too dark, and I want to change it with a lighter color.
Can you help me?

**Comment by gryf** [comment]
Hi,

You can change it [here, on line 278](https://github.com/gryf/wombat256grf/blob/25a4b5d90d7764d45645cbd6a1d992f1543b9931/colors/wombat256grf.vim#L278). Second argument for function X is a font color, third is background, which I presume you want to change. HTH!

**Comment by hzonuz** [comment]
Thanks a lot!
