### ISSUE TITLE
Feature request: black background

### ISSUE THREAD

**Issue by baldr9** [gryf/wombat256grf#2]
How can you make the background black instead of the default muddy brown?

**Comment by gryf** [comment]
Third parameter to `hi` function is the background color, which is gray actually, not "muddy brown". You can change it here: https://github.com/gryf/wombat256grf/blob/98a08140acffe78a1d812ee0c8143adf77d991f8/colors/wombat256grf.vim#L151

**Comment by baldr9** [comment]
thanks!
